language: node_js
sudo: required
node_js:
  - '8'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - libstdc++6
env:
  global:
  - ENCRYPTION_LABEL: "a4adbc32d1aa"
  - COMMIT_AUTHOR_EMAIL: "j.laville@qwant.com"

script:
  - git clone https://github.com/QwantResearch/map-style-builder.git
  - npm install mapbox-gl semver
  - cd map-style-builder
  - npm install
  - npm test -- ../ --icons=true
  - npm run build_all -- --style-dir=../ --conf=./prod_conf.json --i18n=fr --webfont=true --icons=true
  - cd ..

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ./release.sh
  on:
    branch: master

services:
  - docker
