language: node_js
sudo: false
node_js:
- '6'
branches:
  only:
  - master
  - "/^v\\d+(\\.\\d+)*$/"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - libstdc++6
env:
  global:
  - ENCRYPTION_LABEL: "a4adbc32d1aa"
  - COMMIT_AUTHOR_EMAIL: "j.laville@qwant.com"
script:
- git clone https://github.com/QwantResearch/map-style-builder.git
- npm install mapbox-gl
- cd map-style-builder
- npm install
- npm run build_all -- --style-dir=../ --conf=./prod_conf.json
deploy:
- cd ..
- git config --local user.name "qwant_travis"
- git config --local user.email "travis@qwant.com"
- npm install semver
- ./release.sh
